const { chromium } = require('/Users/vamsikrishnavh/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert = require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true});
 try {
 const page=await browser.newPage({viewport:{width:1440,height:900}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.clock.install();
 await page.route('**/main.js*',async route=>{
  const response=await route.fetch();
  await route.fulfill({response,body:await response.text()+`
   // Physics and payout regression uses a small canvas; visual-check covers full resolution.
   renderer.setPixelRatio(.35); renderer.transmissionResolutionScale=.25; renderer.shadowMap.enabled=false; resize();
   const originalDebris=animateDebris;
   const half=geo.boundingBox.getSize(new THREE.Vector3()).multiplyScalar(.5);
   const visualShape=new RAPIER.Cuboid(half.x,half.y,half.z);
   window.debrisViolations=[];
   animateDebris=(dt)=>{
    originalDebris(dt);
    const active=blocks.filter(b=>b.visible);
    for(const [i,block] of active.entries()){
     block.updateMatrix();
     const bounds=geo.boundingBox.clone().applyMatrix4(block.matrix);
     if(bounds.min.y<tableTop-.005)window.debrisViolations.push({floor:bounds.min.y,position:block.position.toArray()});
     for(const other of active.slice(i+1)){
      const contact=visualShape.contactShape(block.position,block.quaternion,visualShape,other.position,other.quaternion,0);
      if(contact && contact.distance<-.005)window.debrisViolations.push({overlap:contact.distance});
     }
    }
   };
   window.debrisAtRest=()=>blocks.filter(b=>b.visible).every(b=>b.userData.resting);
   window.musicActive=()=>musicTimer!==undefined && musicBus!==null;
   window.testFullBreak=()=>{rebuild(28);state.phase='broken';startDebris();};
   window.testWin=(target)=>{state.target=target;state.phase='running';settle(true,100);};
   window.celebrationCount=()=>celebration.visible?confetti.filter(p=>p.visible).length:0;
   window.testHistory=()=>{state.history=[2.96,1.08,12.60,3.84,.73].map((at,index)=>({at,target:2.5,bet:10000,payout:index===4?0:25000,won:index!==4}));renderRoundHistory();};
  `});
 });
 await page.addInitScript(()=>{localStorage.setItem('stacks:intro-seen:v1','1');crypto.getRandomValues=(a)=>{a.fill(Math.floor(.00965*4294967296)-1);return a;};});
 await page.goto(process.env.STACKS_URL || 'http://127.0.0.1:4175');
 await page.waitForSelector('canvas');
 await page.clock.runFor(500);
 assert.match(await page.locator('#gameLoader').getAttribute('class'),/is-splash/);
 assert.equal(await page.locator('#gameLoader').getAttribute('aria-label'),'STACKS ready');
 await page.clock.runFor(2000);
 assert.equal(await page.locator('#gameLoader').getAttribute('hidden'),'');
 const pixels=await page.locator('canvas').evaluate(c=>{const g=c.getContext('webgl2');const p=new Uint8Array(c.width*c.height*4);g.readPixels(0,0,c.width,c.height,g.RGBA,g.UNSIGNED_BYTE,p);return p.filter((v,i)=>i%4===3&&v>0).length;});
 assert(pixels>1000,'Canvas must render');
 assert.equal(await page.locator('#target').getAttribute('type'),'range');
 assert.equal(await page.locator('#settingsDrawer #turbo').count(),0);
 assert.equal(await page.locator('.bottom-playbar #turbo').count(),1);
 await page.locator('#turbo').click();
 assert.equal(await page.locator('#turbo').getAttribute('aria-checked'),'true');
 assert.match(await page.locator('#turbo').getAttribute('aria-label'),/faster round reveals/);
 await page.locator('#turbo').click();
 assert.equal(await page.locator('#turbo').getAttribute('aria-checked'),'false');
 assert.equal(await page.locator('.recent-values li').count(),0);
 assert.equal(await page.locator('.recent-results').getAttribute('hidden'),'');
 await page.evaluate(()=>window.testHistory());
 assert.deepEqual(await page.locator('.recent-values li').allTextContents(),['2.96x','1.08x','12.60x','3.84x','0.73x']);
 assert.equal(await page.locator('.recent-values li.latest').textContent(),'2.96x');
 assert.equal(await page.locator('.recent-results').getAttribute('hidden'),null);
 await page.locator('#target').focus();await page.keyboard.press('ArrowRight');
 assert.equal(await page.locator('#prediction').inputValue(),'2.51');
 await page.keyboard.press('ArrowLeft');
 await page.locator('#target').fill('460');
 assert.equal(await page.locator('#prediction').inputValue(),'10.00');
 await page.locator('#target').fill('1000');
 assert.equal(await page.locator('#prediction').inputValue(),'1000.00');
 await page.locator('#prediction').fill('2.50');
 await page.locator('#barSettings').click();
 assert.equal(await page.locator('#settingsDrawer').getAttribute('class'),'settings-drawer open');
 await page.locator('.play-button').click();
 assert.equal(await page.locator('#settingsDrawer').getAttribute('class'),'settings-drawer');
 assert(await page.evaluate(()=>window.musicActive()),'Music starts with play');
 await page.locator('#barSettings').click();
 await page.locator('#music').click();
 assert.equal(await page.evaluate(()=>window.musicActive()),false,'Music can be muted');
 assert.equal(await page.locator('#sound').getAttribute('aria-checked'),'true','Music and effects are independent');
 await page.locator('#music').click();
 assert(await page.evaluate(()=>window.musicActive()),'Music can resume');
 await page.locator('#closeSettings').click();
 const before=await page.locator('canvas').evaluate(c=>c.toDataURL());
 await page.clock.runFor(800);
 assert.notEqual(await page.locator('canvas').evaluate(c=>c.toDataURL()),before);
 assert(await page.locator('.play-button').isDisabled());
 assert(await page.locator('#target').isDisabled());
 assert(await page.locator('#prediction').isDisabled());
 await page.keyboard.press('Space');
 await page.clock.fastForward(11000);
 assert(await page.locator('.play-button').isDisabled(),'Continue past prediction');
 assert.equal(await page.locator('.round-message').count(),0);
 assert.equal(await page.locator('#live-multiplier').textContent(),'Live '+await page.locator('.multiplier').textContent());
 assert.equal(await page.locator('#prediction').inputValue(),'2.50');
 assert.equal(await page.locator('.balance strong').textContent(),'12,350.00');
 await page.clock.fastForward(60000);
 await page.clock.runFor(1000);
 assert.equal(await page.locator('.win-amount').textContent(),'250.00');
 assert.equal(await page.locator('.win-detail').count(),0);
 assert.equal(await page.locator('.multiplier').textContent(),'100.00x');
 assert.equal(await page.locator('.win-title').textContent(),'YOU WIN','Tier uses prediction, not revealed 100x');
 assert.equal(await page.locator('#live-multiplier').textContent(),'');
 assert.equal(await page.locator('.balance strong').textContent(),'12,600.00');
 await page.clock.fastForward(5000);
 assert.equal(await page.locator('.balance strong').textContent(),'12,600.00');
 await page.screenshot({path:__dirname+'/desktop.png'});
 await page.evaluate(()=>{crypto.getRandomValues=(a)=>{a.fill(Math.floor(.99*4294967296));return a;};});
 await page.locator('.play-button').click();
 assert.equal(await page.locator('.round-message').count(),0);
 assert.equal(await page.locator('.stage-status').count(),0);
 assert.equal(await page.locator('.balance strong').textContent(),'12,500.00');
 await page.clock.runFor(10000);
 assert.deepEqual(await page.evaluate(()=>window.debrisViolations),[],'Cubes must not cross the tabletop');
 assert(await page.evaluate(()=>window.debrisAtRest()),'Cubes must settle on the table');
 await page.screenshot({path:__dirname+'/break.png'});
 await page.locator('.toggle-pill').click();
 assert.equal(await page.locator('#settingsDrawer').getAttribute('class'),'settings-drawer open autoplay-open');
 assert.equal(await page.locator('#settingsDrawer h2').textContent(),'Autoplay settings');
 assert.equal(await page.locator('#sound').isVisible(),false);
 assert.equal(await page.locator('#rounds').isVisible(),true);
 await page.locator('#rounds').fill('2');
 await page.locator('#startAutoplay').click();
 assert.equal(await page.locator('#settingsDrawer').getAttribute('class'),'settings-drawer');
 assert.equal(await page.locator('.toggle-pill').getAttribute('aria-checked'),'true');
 assert.equal(await page.locator('#autoplayProgress').textContent(),'1/2');
 assert.equal(await page.locator('#autoplayProgress').isVisible(),true);
 await page.clock.runFor(2000);
 assert.equal(await page.locator('.toggle-pill').getAttribute('aria-checked'),'false');
 assert.equal(await page.locator('.balance strong').textContent(),'12,300.00');
 await page.locator('#bet').fill('-100');await page.locator('.play-button').click();
 assert.match(await page.locator('#bet').evaluate(input=>input.validationMessage),/valid stake/);
 await page.setViewportSize({width:390,height:844});await page.clock.runFor(300);
 await page.screenshot({path:__dirname+'/mobile.png'});
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'No horizontal overflow');
 await page.evaluate(()=>window.testFullBreak());
 await page.clock.runFor(15000);
 assert.deepEqual(await page.evaluate(()=>window.debrisViolations),[],'Full tower must not intersect itself or the table');
 assert(await page.evaluate(()=>window.debrisAtRest()),'Full tower must settle');
 await page.screenshot({path:__dirname+'/break-pile.png'});
 await page.evaluate(()=>window.testWin(10));
 assert.equal(await page.locator('.win-title').textContent(),'BIG WIN');
 assert.equal(await page.evaluate(()=>window.celebrationCount()),72);
 await page.evaluate(()=>window.testWin(25));
 assert.equal(await page.locator('.win-title').textContent(),'MEGA WIN');
 assert.equal(await page.evaluate(()=>window.celebrationCount()),96);
 await page.clock.runFor(600);
 await page.screenshot({path:__dirname+'/mega-win.png'});
 await page.emulateMedia({reducedMotion:'reduce'});
 await page.evaluate(()=>window.testWin(25));
 assert.equal(await page.evaluate(()=>window.celebrationCount()),0);
 assert.deepEqual(errors,[]);
 console.log('PASS: prediction slider, locked controls, full 100x reveal, exact 2.5x payout, single credit, loss, autoplay, canvas and mobile layout.');
 } finally {await browser.close();}
})().catch(e=>{console.error(e);process.exit(1);});
